### ISSUE TITLE
adding a new vehicle 

### ISSUE THREAD

**Issue by PauloModding** [4c65736975/cameraSystem#10]
I would like to know how to add new vehicles to your mod please thank you

**Comment by 4c65736975** [comment]
https://github.com/4c65736975/cameraSystem#vehicle-integration

**Comment by PauloModding** [comment]
Hi, thanks for answering, so if I've understood correctly, I need to add the cameraSystem lines to the CameraRenderElement.lua script, right?

**Comment by 4c65736975** [comment]
> Hi, thanks for answering, so if I've understood correctly, I need to add the cameraSystem lines to the CameraRenderElement.lua script, right?

Not at all. You don't have to modify code. You just have to add configurations to vehicle.xml, it's just a simple implementation like others specializations.

![Untitled](https://github.com/4c65736975/cameraSystem/assets/107006334/d4accee8-fc83-417d-8959-3ee24940d993)

**Comment by PauloModding** [comment]
so xml from my vehicle is it? thanks for your reply

**Comment by PauloModding** [comment]
I would like to add this on mods I create myself

**Comment by PauloModding** [comment]
thanks for the kind help

**Comment by PauloModding** [comment]
I succeeded thank you I can add to the time I want?

**Comment by 4c65736975** [comment]
> I succeeded thank you I can add to the time I want?

As much as you want and as long as the game will allow you ;)

**Comment by PauloModding** [comment]
it's great and to name the cameras like rear left right or other I have to do how.

**Comment by 4c65736975** [comment]
> it's great and to name the cameras like rear left right or other I have to do how.

Everything you need you have [here](https://github.com/4c65736975/cameraSystem#vehicle-integration)
Or you can wait for video tutorial.

**Comment by PauloModding** [comment]
ok super thank you very much for helping me

**Comment by PauloModding** [comment]
everything works perfectly thank you
