### ISSUE TITLE
Feature Request Indoor Camera

### ISSUE THREAD

**Issue by djdanby** [4c65736975/cameraSystem#11]
It would be cool if you could put the cameras in the vehicle, in the monitors, instead of having them displayed as a hud. If that is at all possible.... Maybe it works like the realGPS mod?!

**Comment by extremefarmer** [comment]
This feature would be great. I hope this is workable. It would make the interior look much more realistic and greatly increase the fun of the game!!

**Comment by MA78MO** [comment]
This Feature dont work with the Giants Engine

**Comment by 4c65736975** [comment]
Duplicate
