### ISSUE TITLE
pipe Configuration+Kamerasystem

### ISSUE THREAD

**Issue by Basti06** [4c65736975/cameraSystem#14]
Guten Abend
Ist es irgendwie möglich das Kamerasystem direkt in eine pipe Configuration hinzuzufügen oder geht dieses nicht?

![2](https://github.com/4c65736975/cameraSystem/assets/75812651/bae468aa-4c4b-4eaa-95de-369b3775cb03)

**Comment by 4c65736975** [comment]
You can use configurationSets

**Comment by Basti06** [comment]
Könnten Sie mir vllt eine Beispiel config zeigen anhand von der pipe configuration? Da ich nicht weiß wie man  diese einbau bzw wie die config aussehen muss

**Comment by 4c65736975** [comment]
> Könnten sie mir ein Beispiel vllt geben da ich nicht weis wie das mit configurationSets funktioniert

``` xml
<configurationSets title="$l10n_configuration_machineType">
  <configurationSet name="set_name" isDefault="true">
    <configuration name="pipe" index="1"/>
    <configuration name="camera" index="1"/>
  </configurationSet>
  <configurationSet name="set_name">
    <configuration name="pipe" index="2"/>
    <configuration name="camera" index="2"/>
  </configurationSet>
</configurationSets>
```

And so on, take a look at default in-game vehicles from data folder
