### ISSUE TITLE
L'ajout de véhicules et remorque / tutoriel d'ajout

### ISSUE THREAD

**Issue by Ghooosty** [4c65736975/cameraSystem#16]
Alors déjà, je tiens avec le plus grand amour, d'avoir crée ce mod, qui manquait sur le jeu ! Merci ! :+1: :+1: :+1: 

Et comme vu dans certaines question ( archivé ) 
Je viens vers vous, pour savoir comment ajouter des véhicule/remorque ( si c'est possible, j'ai cru voir que ce n'était pas le cas encore actuellement 07/08/23 )

Pourriez vous faire un tutoriel Vidéo ou par autre moyen, je ne connais pas tout ce qui et dans le mod ( langage et autre ) et votre communauté grandissante fait que pas mal de monde ce demande comment faire cela ! :100: 

En vous remerciant du travail effectué et et de cet qualité de travail ! :clap: 
Ghoosty

**Comment by 4c65736975** [comment]
Thanks ;) Such a tutorial will definitely appear, in the coming days there will also be an update.
