### ISSUE TITLE
HUD camera display size.

### ISSUE THREAD

**Issue by onehandclapping** [4c65736975/cameraSystem#17]
I love this mod! As a retired programmer with not a clue about modding I'm full of admiration. OK that's the sugar, now...  :-)

It would be nice to be able to change the size of the camera display even if only a choice of "Small, medium, large". I guess you'd need to add a little config file for that so people can easily change it. Reason (for me) being I've set my harvester up with a workarea camera to show the cutter but with the current display it's still hard to see exactly where the edge of the cutter is.

Failing that what can I change in the code to make the view say 50% bigger?

**Comment by SbSh-DNA-ModDing** [comment]
hi, ich denke hier: 
/cameraSystem/tree/main/src/gui/hud/VehicleCameraSystemHUDExtension.lua
Zeile 133
Sollte relativ selbsterkländ sein als Programmierer

**Comment by onehandclapping** [comment]
Verstanden, danke.

I still think it would be nice as a configuration option though.

**Comment by 4c65736975** [comment]
It will be possible to change the display position of the camera to just below the money box etc. and in this position the display will be larger.
