### ISSUE TITLE
no particle animation

### ISSUE THREAD

**Issue by Toni071187** [4c65736975/cameraSystem#18]
Hey, super Mod!

Ich habe die camera bei einem Häcksler verbaut als PipeCam. Es funktioniert soweit, nur wird kein Partikeleffect gezeigt.
Bei einem Mähdrescher habe ich in der Rückfahrkamera die Chopperpartikel, jedoch keine an der Pipe.

Wie kann ich das beheben?

Beste Grüße

**Comment by 4c65736975** [comment]
Thanks, due to a Giants Engine bug I can't get it to show the particles in the official modhub as it throws an error from time to time. But you can manually improve it [tutorial](https://github.com/4c65736975/cameraSystem#improvements)

**Comment by Toni071187** [comment]
Thank you, now it works perfectly.

best regards
