### ISSUE TITLE
Tried to integrate the CS in a Mod

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [4c65736975/cameraSystem#19]
Hi, I tried to install the cameraSystem in this [mod harvester](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=261338&title=fs2022)

but it doesn't show any cam hud. It is aktivated in the shop config.
All other cam in other vehicles that i installed works fine.

**Comment by 4c65736975** [comment]
`
<cameraSystem>
  <cameraConfigurations>
    <cameraConfiguration name="$l10n_configuration_valueNo" price="0"/>
    <cameraConfiguration name="$l10n_configuration_valueYes" price="200">
      <camera node="M300MCSLC" fov="90" rotation="-5 0 0"/>
    </cameraConfiguration>
  </cameraConfigurations>
</cameraSystem>
`

Works fine

**Comment by SbSh-DNA-ModDing** [comment]
![grafik](https://github.com/4c65736975/cameraSystem/assets/4678246/93061e2a-a097-49ca-a66e-c3718f8e051c)
I can't activate the cam :(

**Comment by 4c65736975** [comment]
> ![grafik](https://user-images.githubusercontent.com/4678246/260840855-93061e2a-a097-49ca-a66e-c3718f8e051c.png) I can't activate the cam :(

Everything works for me, also with this modification. Send logs, give some details... I can't read minds

**Comment by SbSh-DNA-ModDing** [comment]
not possible to activate it in this harvester!

**Comment by 4c65736975** [comment]
> not possible to activate it in this harvester!

As I mentioned, everything works perfectly for me..
[FS22_Agco_Leveling_Pack.zip](https://github.com/4c65736975/cameraSystem/files/12403262/FS22_Agco_Leveling_Pack.zip)
![Farming Simulator 22 8_22_2023 1_05_45 AM](https://github.com/4c65736975/cameraSystem/assets/107006334/f549f327-81ea-4143-bbda-a801f9592378)

Maybe try newer version: [new](https://github.com/4c65736975/cameraSystem/tree/feature_implements_cameras)
