### ISSUE TITLE
Precision Farming Conflict

### ISSUE THREAD

**Issue by davarravad** [4c65736975/cameraSystem#21]
With vehicles that do not have camera system enabled, the Precision Farming info box will show up when you enter a vehicle and keep cycling the slide animation for the duration you are in that vehicle.  

If you open the F1 menu it will stop, but if closed it will cycle the animation.  

If vehicle does have camera system enabled on it, it will show, and stay as it should with camera below it.  

https://github.com/4c65736975/cameraSystem/assets/12216243/a500bc8d-9836-443e-9c07-3ec538c05146

I removed Camera System from my active mods and Precision Farming works as it should.  I only have this issue when the Camera System mod is enabled.

**Comment by 4c65736975** [comment]
Problem in version v1.0.0.1 unnoticed
