### ISSUE TITLE
[Enhancement] BR translation

### ISSUE THREAD

**Issue by Myiamoto86** [4c65736975/cameraSystem#22]
Dear friend,

Good evening.

I have the br translation available. I hope to be able to contribute to future updates and other mods.

Please find the file attached.
[modDesc.txt](https://github.com/4c65736975/cameraSystem/files/12413178/modDesc.txt)

Cheers.

**Comment by 4c65736975** [comment]
Feel free to clone [last branch](https://github.com/4c65736975/cameraSystem/tree/feature_implements_cameras), create new branch from it and create pull request ;)
