### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by MafiaxPhantom** [4c65736975/cameraSystem#28]
After some investigation I found that the Camera Sytem mod conflicts with the "Filllevel Warning" mod for combine harvesters, causing the camera display to load with "Lizard" rather than the brand of machine I was using.

I believe this is caused because both mods look for the current vehicles brand in some way, Camera Sytem uses it for the loading of display, and "Filllevel Warning" mod uses it to identify which buzzer tone the combine harvesters uses. Although I cannot be 100% sure as I'm not a Modder myself.

Any chance this could be looked at? Although it's not a game breaking issue. Thank you.

**Comment by Radu-Robu** [comment]
Can confirm there is a mod conflict between those 2 and so far only with harvesters.

**Comment by Gordon-Dry** [comment]
FS22_CameraSystem\src\gui\hud\CameraSystemHUDExtension.lua
line 40
`local brand = vehicle.brand.imageShopOverview or g_brandManager:getBrandByIndex(Brand.LIZARD).imageShopOverview`
vs.
FS22_Filllevelwarning\fillLevelWarning.lua
line 52
`self.brand = self.xmlFile:getValue ("vehicle.storeData.brand" , false)`

The approach totally differs, but creates an issue whatsoever.
I don't know if this is a simple fiddle and solution done or needs some more work to get fixed.

**Comment by 4c65736975** [comment]
The problem occurs because Filllevel Warning overwrites self.brand (vehicle brand) `self.brand = self.xmlFile:getValue ("vehicle.storeData.brand" , false)` for some reason, at least irrational, if not stupid. You must report this to the author of this modification so that he can remove this piece of code that I don't understand why is there.
