### ISSUE TITLE
Assistance with adding the mod to more vehicles

### ISSUE THREAD

**Issue by Radu-Robu** [4c65736975/cameraSystem#29]
I am trying to basically figure out how to implement the mod into more modded vehicles. So far I have copied the camera implementation from a base game Axion 800 to a modded Axion 800 special edition by copy-pasting the appropriate xml lines in the CameraSystemDefaultVehicleData.xml.

I figured out the next step would be to implement the camera into the DeutzFahr Series 6 mod [https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=269601&title=fs2022](url) with the same method.

The lines I tried modifying are the following.
`<vehicle xmlFilename="mod/FS22_DeutzSeries6/vehicles/series6/series6.xml" price="400">
      <cameras>
        <camera nodeName="series6_main_component1" name="$l10n_ui_cameraSystem_nameRear" fov="45" translation="0 3.19142628 -1.57729161" rotation="-50 0 0"/>
      </cameras>
    </vehicle>
	<vehicle xmlFilename="mod/FS22_DeutzSeries6/vehicles/series6_4/series6_4.xml" price="400">
      <cameras>
        <camera nodeName="series6_main_component1" name="$l10n_ui_cameraSystem_nameRear" fov="45" translation="0 3.19142628 -1.57729161" rotation="-50 0 0"/>
      </cameras>
    </vehicle>
	<vehicle xmlFilename="mod/FS22_DeutzSeries6/vehicles/series6_4T5/series6_4T5.xml" price="400">
      <cameras>
        <camera nodeName="series6_main_component1" name="$l10n_ui_cameraSystem_nameRear" fov="45" translation="0 3.19142628 -1.57729161" rotation="-50 0 0"/>
      </cameras>
    </vehicle>
	<vehicle xmlFilename="mod/FS22_DeutzSeries6/vehicles/series6T5/series6T5.xml" price="400">
      <cameras>
        <camera nodeName="series6_main_component1" name="$l10n_ui_cameraSystem_nameRear" fov="45" translation="0 3.19142628 -1.57729161" rotation="-50 0 0"/>
      </cameras>
    </vehicle>
    <vehicle xmlFilename="data/vehicles/deutzFahr/series7/series7.xml" price="400">
      <cameras>
        <camera nodeName="series7_main_component1" name="$l10n_ui_cameraSystem_nameRear" fov="45" translation="0 3.19142628 -1.57729161" rotation="-50 0 0"/>
      </cameras>
    </vehicle>`

With this I have achieved a partial success. The camera system option shows up in the shop. However, when actually inside the tractor, there's no option to turn on the camera system, and it just doesn't work at all.
The last lines in correspond to the DeutzFahr series 7 tractor which is a base game vehicle which does work. 

The mod in question has a different internal file structure than the DF Series7, so maybe that's the issue?
![image](https://github.com/4c65736975/cameraSystem/assets/79966181/8863f207-e121-402b-8d9a-9d36ca85f3cb)

**Comment by Radu-Robu** [comment]
I have found the issue. Not Camera System related, but the DF Series6 mod had mismatched node names between the mappings and the i3d. Closing the issue.

**Comment by 4c65736975** [comment]
> I have found the issue. Not Camera System related, but the DF Series6 mod had mismatched node names between the mappings and the i3d. Closing the issue.

You can always take a look at log, if there is problem with setting up node for camera there should be error.
