### ISSUE TITLE
List of default Vehicles

### ISSUE THREAD

**Issue by Tensuko** [4c65736975/cameraSystem#3]
Maybe not the 100% correct ingame Name, but a rough overview.
Cool mod btw! :)

Small
- Claas Arion 600
- CaseIH Maxxum 145CVX
- Massey Ferguson Series 6S
- John Deere Series 6M
- New Holland T6
- Fendt Vario 300

Medium
- Deutz Fahr Series 8
- John Deere Series 6R
- New Holland T7
- Massey Ferguson Series 7710S

Large
- Fendt Vario 1000
- Claas Axion 960TT
- John Deere Series 7R

Harvester
- Claas Lexion 8000
- New Holland CR Series
- Fendt Ideal
- John Deere X9 1100
- John Deere T560
- New Holland CH Series

Forage Harvester
- Krone BigX1180
- John Deere Series 9000

Potato Harvester
- Grimme Ventor 4150

Beet Harvester
- Ropa Panther 2
- Grimme Rexor 6300

Grape Harvester
- New Holland Braud 9070L

Olive Harvester
- New Holland Braud 9090X

**Comment by MA78MO** [comment]
There is the List : https://github.com/4c65736975/cameraSystem/blob/main/VEHICLES.md
