### ISSUE TITLE
Help with camera positions

### ISSUE THREAD

**Issue by Radu-Robu** [4c65736975/cameraSystem#30]
![image](https://github.com/4c65736975/cameraSystem/assets/79966181/641c143d-c969-4b73-997a-2d6c011a0ada)

I'm very new to the innards of Farming Sim modding and I would like to know how you managed to get such precise values for the camera rotation and translation.

**Comment by 4c65736975** [comment]
Just set up template transform in Giants Editor and copied rotation and translation values.

**Comment by Radu-Robu** [comment]
Do you have a link to a tutorial where I can learn how to set them up? I have very little knowledge about the Giants Editor

Nevermind, figured it out.

**Comment by 4c65736975** [comment]
For now you can use only this [integration tutorial](https://github.com/4c65736975/cameraSystem#vehicle-integration). I will make video tutorial soon.

**Comment by Radu-Robu** [comment]
I have not managed to get the vehicle integration working, but I did manage to add cameras by editing the default vehicles XML.

**Comment by 4c65736975** [comment]
> I have not managed to get the vehicle integration working, but I did manage to add cameras by editing the default vehicles XML.

Send your cameraSystem configurations part of code, I will let you know if something is wrong.
