### ISSUE TITLE
schneidwerk

### ISSUE THREAD

**Issue by Basti06** [4c65736975/cameraSystem#31]
Kann man diesen code noch benutzen um das Camerasystem in ein schneidwerk einzubauen?
oder muss man noch etwas machen da ich den das so bei einem Mähdrescher benutze und da Funktioniert es nur bei dem Schneidwerk nicht

![Unbenannt](https://github.com/4c65736975/cameraSystem/assets/75812651/ed0bffa1-59e2-460c-9541-6e31ba86666e)

**Comment by 4c65736975** [comment]
Absolutely, the configuration code has not been changed
