### ISSUE TITLE
Video how to add this mod

### ISSUE THREAD

**Issue by Blazej08** [4c65736975/cameraSystem#4]
Hello,

I have zero ideas how to create and edit mods, are you planing maybe to add a video to show how to add this mod to vehicles that dont have the system? 

Have a nice day :)

**Comment by 4c65736975** [comment]
Hi, I didn't plan this at all. But maybe I'll record such a tutorial ;) You too ;)

**Comment by yinyin80** [comment]
sa serai possible ou pas d'avoir un tuto pour placer les camera sur les vehicules
