### ISSUE TITLE
High CPU Temp when using this mod

### ISSUE THREAD

**Issue by Foxbait** [4c65736975/cameraSystem#5]
Tested this with only this mod and I get high cpu temp.

**Comment by 4c65736975** [comment]
What is your computer specification? Modification is demanding, but there is nothing I can do about it. It's because of the engine limitation. The log is clear ?

**Comment by kapatyh** [comment]
скрипт на отключение мульчирования будет ?

**Comment by kapatyh** [comment]
Я понимаю что не та тема )) Я писал в  другом блоке но там ответа нет. Скрипт будет очень полезным в игре.

**Comment by 4c65736975** [comment]
Lack of activity
