### ISSUE TITLE
Not working on a trailer

### ISSUE THREAD

**Issue by Rolandios1999** [4c65736975/cameraSystem#6]
I cant get it to work on a trailer, is it only working when using Drivable ?

**Comment by 4c65736975** [comment]
The update will be in few days available on GitHub ;)

**Comment by Rolandios1999** [comment]
> The update will be in few days available on GitHub ;)

Seen it after i posted sorry ! amazing work, config will work the same ?

**Comment by 4c65736975** [comment]
Thanks 😊 It will 😉
