### ISSUE TITLE
Kamera HUD position 

### ISSUE THREAD

**Issue by Green0Seven** [4c65736975/cameraSystem#8]
Hallo, Kann man die  Position der HUD Kamera Bild (Standard: Links) auf Rechts ändern und wie?

LG
![1Unbenannt](https://github.com/4c65736975/cameraSystem/assets/89019942/6457bc03-0864-4a24-948b-94e44c6766a5)

**Comment by 4c65736975** [comment]
Actually there is no such option for now, but I thought about it and there will be such a feature in future updates.

**Comment by Green0Seven** [comment]
Das wehr natürlich super. Danke für die Schnelle Antwort.
Ein Schön Tag noch. ;) 

LG

**Comment by 4c65736975** [comment]
> Das wehr natürlich super. Danke für die Schnelle Antwort. Ein Schön Tag noch. ;)
> 
> LG

Danke dir auch einen schönen Tag ;)
